// Generated by tools/build_songs.py — do not edit by hand.
window.SONGS = [
 {
  "id": "neon-mile",
  "title": "Neon Mile",
  "genre": "Synthwave",
  "bpm": 100,
  "key": "A minor",
  "difficulty": "Easy",
  "blurb": "Wide J-6 pad, octave-jumping S-1 bass. The one to start with \u2014 four chords, sixteen steps, sounds finished in about two minutes.",
  "j6": {
   "chordSet": "Synthwave / 80s Pop",
   "style": "Pad or slow Arp",
   "variation": "1\u20133 (keep it simple)",
   "knobs": {
    "CUTOFF": "1 o'clock",
    "RESONANCE": "9 o'clock",
    "ATTACK": "10 o'clock (slow-ish swell)",
    "RELEASE": "3 o'clock",
    "REVERB": "2 o'clock",
    "DELAY": "11 o'clock",
    "CHORUS": "ON \u2014 this is the JUNO sound"
   },
   "prog": [
    "Am",
    "F",
    "C",
    "G"
   ],
   "chords": [
    [
     57,
     60,
     64
    ],
    [
     53,
     57,
     60
    ],
    [
     48,
     52,
     55
    ],
    [
     55,
     59,
     62
    ]
   ],
   "chordNames": [
    [
     "A3",
     "C4",
     "E4"
    ],
    [
     "F3",
     "A3",
     "C4"
    ],
    [
     "C3",
     "E3",
     "G3"
    ],
    [
     "G3",
     "B3",
     "D4"
    ]
   ]
  },
  "s1": {
   "role": "Bass",
   "div": 4,
   "patch": {
    "WAVE": "SAW",
    "SUB": "1 o'clock",
    "CUTOFF": "11 o'clock",
    "RESONANCE": "10 o'clock",
    "ENV MOD": "12 o'clock",
    "DECAY": "10 o'clock",
    "ACCENT": "1 o'clock",
    "LFO": "off"
   },
   "steps": [
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 29,
     "name": "F1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 36,
     "name": "C2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 31,
     "name": "G1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 31,
     "name": "G1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 31,
     "name": "G1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 31,
     "name": "G1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 31,
     "name": "G1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    }
   ]
  },
  "midi": "midi/neon-mile.mid"
 },
 {
  "id": "acid-rain",
  "title": "Acid Rain",
  "genre": "Acid Techno",
  "bpm": 130,
  "key": "A minor",
  "difficulty": "Medium",
  "blurb": "The reason you buy an S-1. Slides and accents doing the classic 303 thing while the J-6 throws short stabs over the top.",
  "j6": {
   "chordSet": "Techno / House",
   "style": "Stab / short Arp",
   "variation": "4\u20136 (busier)",
   "knobs": {
    "CUTOFF": "12 o'clock",
    "RESONANCE": "1 o'clock",
    "ATTACK": "full left (instant)",
    "RELEASE": "9 o'clock (very short)",
    "REVERB": "10 o'clock",
    "DELAY": "1 o'clock",
    "CHORUS": "OFF"
   },
   "prog": [
    "Am",
    "Am",
    "Dm",
    "E"
   ],
   "chords": [
    [
     57,
     60,
     64
    ],
    [
     57,
     60,
     64
    ],
    [
     50,
     53,
     57
    ],
    [
     52,
     56,
     59
    ]
   ],
   "chordNames": [
    [
     "A3",
     "C4",
     "E4"
    ],
    [
     "A3",
     "C4",
     "E4"
    ],
    [
     "D3",
     "F3",
     "A3"
    ],
    [
     "E3",
     "G#3",
     "B3"
    ]
   ]
  },
  "s1": {
   "role": "Acid bass",
   "div": 4,
   "patch": {
    "WAVE": "SAW",
    "SUB": "off",
    "CUTOFF": "9 o'clock (low \u2014 let the env open it)",
    "RESONANCE": "3 o'clock (high, that's the squelch)",
    "ENV MOD": "2 o'clock",
    "DECAY": "11 o'clock",
    "ACCENT": "3 o'clock",
    "LFO": "off"
   },
   "steps": [
    {
     "n": 33,
     "name": "A1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 40,
     "name": "E2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 40,
     "name": "E2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 38,
     "name": "D2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 33,
     "name": "A1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 38,
     "name": "D2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 38,
     "name": "D2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 50,
     "name": "D3",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 50,
     "name": "D3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 38,
     "name": "D2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 40,
     "name": "E2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 40,
     "name": "E2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 44,
     "name": "G#2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 40,
     "name": "E2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 47,
     "name": "B2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 47,
     "name": "B2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 44,
     "name": "G#2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null
   ]
  },
  "midi": "midi/acid-rain.mid"
 },
 {
  "id": "deep-end",
  "title": "Deep End",
  "genre": "Deep House",
  "bpm": 122,
  "key": "F minor",
  "difficulty": "Medium",
  "blurb": "Lush 7th chords on the J-6, round sub bass on the S-1. Turn the S-1 cutoff down until you feel it more than you hear it.",
  "j6": {
   "chordSet": "House / Neo Soul",
   "style": "Chord + Arp",
   "variation": "3\u20135",
   "knobs": {
    "CUTOFF": "12 o'clock",
    "RESONANCE": "10 o'clock",
    "ATTACK": "9 o'clock",
    "RELEASE": "1 o'clock",
    "REVERB": "2 o'clock",
    "DELAY": "12 o'clock",
    "CHORUS": "ON"
   },
   "prog": [
    "Fm7",
    "Bbm7",
    "Eb7",
    "Abmaj7"
   ],
   "chords": [
    [
     53,
     56,
     60,
     63
    ],
    [
     46,
     49,
     53,
     56
    ],
    [
     51,
     55,
     58,
     61
    ],
    [
     44,
     48,
     51,
     55
    ]
   ],
   "chordNames": [
    [
     "F3",
     "G#3",
     "C4",
     "D#4"
    ],
    [
     "A#2",
     "C#3",
     "F3",
     "G#3"
    ],
    [
     "D#3",
     "G3",
     "A#3",
     "C#4"
    ],
    [
     "G#2",
     "C3",
     "D#3",
     "G3"
    ]
   ]
  },
  "s1": {
   "role": "Sub bass",
   "div": 4,
   "patch": {
    "WAVE": "SQUARE",
    "SUB": "full right (this is the whole point)",
    "CUTOFF": "9 o'clock",
    "RESONANCE": "full left",
    "ENV MOD": "10 o'clock",
    "DECAY": "12 o'clock",
    "ACCENT": "11 o'clock",
    "LFO": "off"
   },
   "steps": [
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    null,
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 32,
     "name": "G#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    null,
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 37,
     "name": "C#2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 27,
     "name": "D#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 27,
     "name": "D#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 27,
     "name": "D#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    null,
    {
     "n": 27,
     "name": "D#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 31,
     "name": "G1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 32,
     "name": "G#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 32,
     "name": "G#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 32,
     "name": "G#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    null,
    {
     "n": 32,
     "name": "G#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 39,
     "name": "D#2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null
   ]
  },
  "midi": "midi/deep-end.mid"
 },
 {
  "id": "lo-fi-sunday",
  "title": "Lo-Fi Sunday",
  "genre": "Lo-Fi / Chill",
  "bpm": 78,
  "key": "C major",
  "difficulty": "Easy",
  "blurb": "Slow, jazzy and forgiving. Nothing here is fast enough to go wrong. Good last-one-before-bed track.",
  "j6": {
   "chordSet": "Neo Soul / Jazz",
   "style": "Chord (long)",
   "variation": "1\u20132",
   "knobs": {
    "CUTOFF": "11 o'clock (dark)",
    "RESONANCE": "9 o'clock",
    "ATTACK": "11 o'clock",
    "RELEASE": "3 o'clock",
    "REVERB": "3 o'clock",
    "DELAY": "1 o'clock",
    "CHORUS": "ON"
   },
   "prog": [
    "Cmaj7",
    "Am7",
    "Dm7",
    "G7"
   ],
   "chords": [
    [
     48,
     52,
     55,
     59
    ],
    [
     45,
     48,
     52,
     55
    ],
    [
     50,
     53,
     57,
     60
    ],
    [
     43,
     47,
     50,
     53
    ]
   ],
   "chordNames": [
    [
     "C3",
     "E3",
     "G3",
     "B3"
    ],
    [
     "A2",
     "C3",
     "E3",
     "G3"
    ],
    [
     "D3",
     "F3",
     "A3",
     "C4"
    ],
    [
     "G2",
     "B2",
     "D3",
     "F3"
    ]
   ]
  },
  "s1": {
   "role": "Soft lead",
   "div": 2,
   "patch": {
    "WAVE": "TRIANGLE / SQUARE",
    "SUB": "10 o'clock",
    "CUTOFF": "1 o'clock",
    "RESONANCE": "10 o'clock",
    "ENV MOD": "10 o'clock",
    "DECAY": "2 o'clock",
    "ACCENT": "10 o'clock",
    "LFO": "slow, light pitch wobble"
   },
   "steps": [
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 67,
     "name": "G4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 71,
     "name": "B4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 69,
     "name": "A4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 67,
     "name": "G4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 60,
     "name": "C4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 67,
     "name": "G4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 65,
     "name": "F4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 69,
     "name": "A4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 72,
     "name": "C5",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 71,
     "name": "B4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 69,
     "name": "A4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 65,
     "name": "F4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 71,
     "name": "B4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 67,
     "name": "G4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null
   ]
  },
  "midi": "midi/lo-fi-sunday.mid"
 },
 {
  "id": "midnight-drive",
  "title": "Midnight Drive",
  "genre": "Dark Techno",
  "bpm": 140,
  "key": "D minor",
  "difficulty": "Medium",
  "blurb": "Fast, moody, relentless. Hold the J-6 chords long and let the S-1 hammer straight sixteenths underneath.",
  "j6": {
   "chordSet": "Techno / Minimal",
   "style": "Arp (fast)",
   "variation": "6\u20139",
   "knobs": {
    "CUTOFF": "11 o'clock",
    "RESONANCE": "2 o'clock",
    "ATTACK": "full left",
    "RELEASE": "12 o'clock",
    "REVERB": "1 o'clock",
    "DELAY": "2 o'clock",
    "CHORUS": "OFF"
   },
   "prog": [
    "Dm",
    "Dm",
    "Bb",
    "C"
   ],
   "chords": [
    [
     50,
     53,
     57
    ],
    [
     50,
     53,
     57
    ],
    [
     46,
     50,
     53
    ],
    [
     48,
     52,
     55
    ]
   ],
   "chordNames": [
    [
     "D3",
     "F3",
     "A3"
    ],
    [
     "D3",
     "F3",
     "A3"
    ],
    [
     "A#2",
     "D3",
     "F3"
    ],
    [
     "C3",
     "E3",
     "G3"
    ]
   ]
  },
  "s1": {
   "role": "Driving bass",
   "div": 4,
   "patch": {
    "WAVE": "SAW",
    "SUB": "12 o'clock",
    "CUTOFF": "10 o'clock",
    "RESONANCE": "1 o'clock",
    "ENV MOD": "1 o'clock",
    "DECAY": "9 o'clock (short and tight)",
    "ACCENT": "2 o'clock",
    "LFO": "off"
   },
   "steps": [
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 38,
     "name": "D2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 33,
     "name": "A1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 38,
     "name": "D2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 29,
     "name": "F1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 26,
     "name": "D1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 46,
     "name": "A#2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 38,
     "name": "D2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 34,
     "name": "A#1",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 40,
     "name": "E2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": true,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 36,
     "name": "C2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": true,
     "gate": 0.9
    },
    {
     "n": 43,
     "name": "G2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    }
   ]
  },
  "midi": "midi/midnight-drive.mid"
 },
 {
  "id": "greensleeves",
  "title": "Greensleeves",
  "genre": "Traditional (public domain)",
  "bpm": 90,
  "key": "A minor",
  "difficulty": "Medium",
  "blurb": "A real tune, so you can hear the S-1 actually sing. Traditional English, out of copyright for about four hundred years.",
  "j6": {
   "chordSet": "Pop / Ballad",
   "style": "Chord (long) or slow Arp",
   "variation": "1\u20133",
   "knobs": {
    "CUTOFF": "12 o'clock",
    "RESONANCE": "9 o'clock",
    "ATTACK": "10 o'clock",
    "RELEASE": "2 o'clock",
    "REVERB": "2 o'clock",
    "DELAY": "10 o'clock",
    "CHORUS": "ON"
   },
   "prog": [
    "Am",
    "C",
    "Am",
    "E"
   ],
   "chords": [
    [
     57,
     60,
     64
    ],
    [
     48,
     52,
     55
    ],
    [
     57,
     60,
     64
    ],
    [
     52,
     56,
     59
    ]
   ],
   "chordNames": [
    [
     "A3",
     "C4",
     "E4"
    ],
    [
     "C3",
     "E3",
     "G3"
    ],
    [
     "A3",
     "C4",
     "E4"
    ],
    [
     "E3",
     "G#3",
     "B3"
    ]
   ]
  },
  "s1": {
   "role": "Lead melody",
   "div": 2,
   "patch": {
    "WAVE": "SQUARE",
    "SUB": "10 o'clock",
    "CUTOFF": "2 o'clock",
    "RESONANCE": "10 o'clock",
    "ENV MOD": "10 o'clock",
    "DECAY": "1 o'clock",
    "ACCENT": "12 o'clock",
    "LFO": "slight pitch vibrato"
   },
   "steps": [
    {
     "n": 57,
     "name": "A3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 60,
     "name": "C4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 65,
     "name": "F4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 59,
     "name": "B3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 56,
     "name": "G#3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 57,
     "name": "A3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 59,
     "name": "B3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 57,
     "name": "A3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 56,
     "name": "G#3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null
   ]
  },
  "midi": "midi/greensleeves.mid"
 },
 {
  "id": "ode-to-joy",
  "title": "Ode to Joy",
  "genre": "Traditional (public domain)",
  "bpm": 120,
  "key": "C major",
  "difficulty": "Easy",
  "blurb": "Beethoven, 1824. Every note is a step or two from the last one, so it's the easiest melody to punch in by hand.",
  "j6": {
   "chordSet": "Pop / Classic",
   "style": "Chord (long)",
   "variation": "1\u20132",
   "knobs": {
    "CUTOFF": "1 o'clock",
    "RESONANCE": "9 o'clock",
    "ATTACK": "9 o'clock",
    "RELEASE": "1 o'clock",
    "REVERB": "1 o'clock",
    "DELAY": "off",
    "CHORUS": "ON"
   },
   "prog": [
    "C",
    "G",
    "C",
    "G"
   ],
   "chords": [
    [
     48,
     52,
     55
    ],
    [
     43,
     47,
     50
    ],
    [
     48,
     52,
     55
    ],
    [
     43,
     47,
     50
    ]
   ],
   "chordNames": [
    [
     "C3",
     "E3",
     "G3"
    ],
    [
     "G2",
     "B2",
     "D3"
    ],
    [
     "C3",
     "E3",
     "G3"
    ],
    [
     "G2",
     "B2",
     "D3"
    ]
   ]
  },
  "s1": {
   "role": "Lead melody",
   "div": 2,
   "patch": {
    "WAVE": "SQUARE",
    "SUB": "11 o'clock",
    "CUTOFF": "2 o'clock",
    "RESONANCE": "9 o'clock",
    "ENV MOD": "10 o'clock",
    "DECAY": "12 o'clock",
    "ACCENT": "12 o'clock",
    "LFO": "off"
   },
   "steps": [
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 65,
     "name": "F4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 67,
     "name": "G4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 67,
     "name": "G4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 65,
     "name": "F4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 60,
     "name": "C4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 60,
     "name": "C4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    {
     "n": 64,
     "name": "E4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    null
   ]
  },
  "midi": "midi/ode-to-joy.mid"
 },
 {
  "id": "rising-sun",
  "title": "House of the Rising Sun",
  "genre": "Traditional (public domain)",
  "bpm": 72,
  "key": "A minor",
  "difficulty": "Easy",
  "blurb": "Traditional American folk. The 6/8 rolling arpeggio sits beautifully on the S-1 \u2014 let the notes ring into each other.",
  "j6": {
   "chordSet": "Ballad / Cinematic",
   "style": "Arp (triplet feel) or long Chord",
   "variation": "2\u20134",
   "knobs": {
    "CUTOFF": "12 o'clock",
    "RESONANCE": "10 o'clock",
    "ATTACK": "10 o'clock",
    "RELEASE": "3 o'clock",
    "REVERB": "3 o'clock",
    "DELAY": "12 o'clock",
    "CHORUS": "ON"
   },
   "prog": [
    "Am",
    "C",
    "D",
    "F"
   ],
   "chords": [
    [
     57,
     60,
     64
    ],
    [
     48,
     52,
     55
    ],
    [
     50,
     54,
     57
    ],
    [
     53,
     57,
     60
    ]
   ],
   "chordNames": [
    [
     "A3",
     "C4",
     "E4"
    ],
    [
     "C3",
     "E3",
     "G3"
    ],
    [
     "D3",
     "F#3",
     "A3"
    ],
    [
     "F3",
     "A3",
     "C4"
    ]
   ]
  },
  "s1": {
   "role": "Rolling arpeggio",
   "div": 2,
   "patch": {
    "WAVE": "TRIANGLE",
    "SUB": "12 o'clock",
    "CUTOFF": "1 o'clock",
    "RESONANCE": "10 o'clock",
    "ENV MOD": "10 o'clock",
    "DECAY": "3 o'clock (long \u2014 let them ring)",
    "ACCENT": "11 o'clock",
    "LFO": "off"
   },
   "steps": [
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 57,
     "name": "A3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 55,
     "name": "G3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 60,
     "name": "C4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 55,
     "name": "G3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 52,
     "name": "E3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 50,
     "name": "D3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 54,
     "name": "F#3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 57,
     "name": "A3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 62,
     "name": "D4",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 57,
     "name": "A3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 54,
     "name": "F#3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null,
    {
     "n": 41,
     "name": "F2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 53,
     "name": "F3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 48,
     "name": "C3",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    {
     "n": 45,
     "name": "A2",
     "acc": false,
     "slide": false,
     "gate": 0.5
    },
    null,
    null
   ]
  },
  "midi": "midi/rising-sun.mid"
 }
];
